### ISSUE TITLE
Update the Project with latest dependencies nd gradle plugin

### ISSUE THREAD

**Issue by Sai-Teja** [psaravan/JamsMusicPlayer#37]
Plz Update the Project with latest dependencies. I tried 1 Hr updating all things and still this isn't even compiling, it's just building after 1 hr of Work. :/

**Comment by sbmaggarwal** [comment]
Try this - https://github.com/psaravan/JamsMusicPlayer/issues/31 .
Issue 31 actually presents a solution.

**Comment by Sai-Teja** [comment]
@sbmaggarwal Thnx!
